services:
  bot:
    build: .
    container_name: deltachat_bouncer
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./data:/app/data
      - ./data/bouncer:/root/.config/bouncer
      - ./data/cmping_cache:/root/.cache/cmping
    environment:
      - DC_DB_DIR=/app/data
      - DB_PATH=/app/data/bouncer.db
      - TZ=UTC
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
